apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: content-aggregation
  tags:
    - node
    - microservice
  links: []
  annotations:
    backstage.io/linguist: git@github.skillsoft.com:pints/content-aggregation-service.git
spec:
  type: service
  lifecycle: production
  owner: PINTS
  system: percipio
  dependsOn:
    - component:msgrelay
  apisConsumedBy: []
