apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: content-discovery-service
  description: Content Discovery Services
  tags:
    - node
    - microservice
  links: []
  annotations:
    backstage.io/linguist: https://github.skillsoft.com/pints/content-discovery-service.git
spec:
  type: service
  lifecycle: production
  owner: PINTS
  system: percipio
  dependsOn:
    - component:content-search-service
    - component:ucs
    - component:academy
    - component:auth-config
    - component:org-api
    - component:provisioning
    - component:scheduler
    - component:ics
    - component:data-extract
    - component:oauth2-provider
    - component:mesg-relay
    - component:share
    - component:aicc-launch
    - component:aicc-launch-path
    - component:lti-launch
    - component:lti-launch-path
    - component:edge-service
    - component:signed-life-time-in-seconds
    - component:pms
    - component:public-share-launch
    - component:salesforce
  apisConsumedBy: []
