apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-common-service
  description: Internal Common Services
  tags:
    - node
    - microservice
  links: []
  annotations:
    backstage.io/linguist: https://github.skillsoft.com/pints/internal-common-service.git
spec:
  type: service
  lifecycle: production
  owner: PINTS
  system: percipio
  dependsOn:
    - component:scheduler
    - component:content_discovery
    - component:org_api
    - component:mesg_relay
  apisConsumedBy: []
